<?php
// partners.php
require_once('../functions/config.php');
?>

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Partners</title>
  <link rel="stylesheet" href="../assets/styles/theme.css" />
  <link rel="stylesheet" href="../assets/styles/partners.css" />
  <link href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
    integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
  <!-- Include the navigation bar -->
  <?php include('../includes/navbar.php'); ?>

  <!-- Image Header -->
  <div class="img-header">
    <h1>Partners</h1>
    <p>Earn and redeem points with our partners</p>
  </div>

  <!-- Partners Section -->
  <div class="wrapper">
    <div class="partners-section">
      <main class="main-container">
        <!-- Filter Buttons -->
        <div class="tabs filter-buttons" role="tablist" aria-label="Partner Categories">
          <!-- Buttons will be dynamically generated by JavaScript -->
        </div>

        <!-- Category Description -->
        <div class="category-description">
          <h1 id="category-title">Oikard Partners</h1>
          <p id="category-description">
            Earn and redeem from brands that fit your lifestyle!
          </p>
        </div>

        <!-- Gallery Grid -->
        <div class="gallery-grid">
          <!-- Gallery items will be dynamically generated by JavaScript -->
        </div>
      </main>
    </div>
  </div>




  <!-- Include footer -->
  <?php include('../includes/footer.php'); ?>

  <!-- JavaScript -->
  <script src="../assets/scripts/changePartnersInfo.js"></script>
  <script src="../assets/scripts/navbar.js"></script>
  <!-- jQuery CDN -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- Isotope CDN -->
  <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
  <!-- imagesLoaded CDN -->
  <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
</body>

</html>